### PR TITLE
Submitting PR for Slack Bot implementation. 

### PR DESCRIPTION
**Pull request by theprogrammedwords**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Comment by theprogrammedwords** [comment]
Please accept PR if it looks good. TY.

**Review by archithdwij — CHANGES_REQUESTED** [review]
@theprogrammedwords Hi! 
Great work on building the bot! Its works precisely but here are a few suggestions that might make your project more effective. 
- Your bot, at present, is not totally aligned with the theme of the project. If you could put a timer or something that pops this advice/ affirmation/ Quotes/ Help automatically from time to time, it will be like a reminder that keeps you in check from time to time. 
- During the time of review, we also felt that instead of the following commands, if your bot could provide updates regarding your daily schedule, tasks (completed/remaining), daily routine check or something like that, your project is going to be a 🌟 . 
- I also wanted to let you know that the demo video was nicely edited, understandable. If you could add a voice over that explains the process, it will be even more helpful. 
Let me know if this could be done. The team is excited to see the modifications you could make so that we add it to our frequently used WFH tools😃 .

**Comment by theprogrammedwords** [comment]
Thank you @archithdwij for suggestions and appreciation. 

- Your bot, at present, is not totally aligned with the theme of the project. If you could put a timer or something that pops this advice/ affirmation/ Quotes/ Help automatically from time to time, it will be like a reminder that keeps you in check from time to time.

> I actually wanted to do this but the slack api and its internal mechanism is taking a lot of time to study and I actually made a classic slack app for authentication but for such actions, app needs to be migrated to newer app. which uses OAuth2 and I am failing that login flow from my end. :( 

- During the time of review, we also felt that instead of the following commands, if your bot could provide updates regarding your daily schedule, tasks (completed/remaining), daily routine check or something like that, your project is going to be a 🌟 .
> Same for this, I need Slack Bolt API usage to schedule the jobs and make to-do things using Interactivity API, but the issue is happening with OAuth2. I am planning to do these steps in long term as I want to understand the slack api mechanism and implement it. 

- I also wanted to let you know that the demo video was nicely edited, understandable. If you could add a voice over that explains the process, it will be even more helpful.
> This can be done by me rightaway. 

Let me know if this could be done. The team is excited to see the modifications you could make so that we add it to our frequently used WFH tools😃 .

>I would try to see if I can add any more features, but due to office been 9-6( give or take one two hours) I am lagging on time to implement this. Can I get some extension if possible ? Because these API Mechanism of Slack is complicated to learn. Let me know what do you think. Thanks. 


**Update : Since Deadline is extended, I would try to acheive all of this and more in the available time. 🤭 🤔**

**Comment by archithdwij** [comment]
@theprogrammedwords Give it your best try 💯

**Comment by theprogrammedwords** [comment]
Yes I am doing it, now I am able to make some stuff, will try my best. 
Can I use middleware integrators (like pipedream/mulesoft) too ? I couldnt Integrate Github / Jira with Bot using code but can do using Middlewares if thats allowed ?

**Comment by sudhanshutiwari264** [comment]
Let us know when you are finished with the requested changes, @theprogrammedwords!
Great work and dedication!

**Comment by theprogrammedwords** [comment]
@sudhanshutiwari264  Thank you so much, I am just preparing the video, rest all I am done with the build. In future will try adding more updates. 😇

**Comment by theprogrammedwords** [comment]
@sudhanshutiwari264 @archithdwij I am almost done except blog part is left. Is it a prerequisite for PR or can be added sooner also ?  Can you review the current version. Thanks

**Comment by theprogrammedwords** [comment]
@archithdwij @sudhanshutiwari264 As much as I could do, I have done. 
Have automated the message flow of advice, affirmation and quotes.
added functionality to schedule messages and remind messages. 
Added Github integrations an Google Calendar Integration for alerts. 

This is what the bot can do now.
   1. Send Github alerts when > you are mentioned,  or a branch is created or an issue is raised for your repository
    2. Sending Google Calendar event alert when you have a meeting within one hour, so you dont miss it.
    3. Can search for your Github repository using /repository_exact_name command. Non Case sensitive.
    4. Set reminders [remindme, remindus] with precision of minutes, hours, or days
    5. Can schedule messages with friendly precision [every minute, every hour, every day] with schedule keyword
    6. Sending quotes, advice and affirmations daily for good vibes.
    ....
    commands [advice, affirmations, quotes, help, remindme, remindus, schedule, /searchrepo]

**Comment by theprogrammedwords** [comment]
Please verify the PR.

**Comment by archithdwij** [comment]
Hey @theprogrammedwords Apologise for the delay in completing the review. You have made good amount of improvement to your project. Good job 🙌

**Review by archithdwij — APPROVED** [review]

**Comment by archithdwij** [comment]
@all-contributors Please add @theprogrammedwords for code, design, infra, idea

**Review by jainaayush01 — COMMENTED** [review]
Congratulations @theprogrammedwords  for getting your PR merged 🥳
Kudos to the great work.

Make sure to submit the blog.

**Comment by theprogrammedwords** [comment]
@jainaayush01  Yes I have submitted the blog and video. Thank you. 🥳 🤭

**Comment by theprogrammedwords** [comment]
> Hey @theprogrammedwords Apologise for the delay in completing the review. You have made good amount of improvement to your project. Good job 🙌

Thank you so much. Means a lot to me. I will keep adding patches in personal repo when I   get time to make it robust. 🤭

**Review by SulthanNK — COMMENTED** [review]
Congrats @theprogrammedwords for getting your PR merged 🎉

**Pull request merged**
