### PR TITLE
Slackmarks - PR

### PR DESCRIPTION
**Pull request by nimisha-yadav**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable). [Added screenshot of extension]
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @nimisha-yadav can you create a demo video and add that video in the readme as well

**Comment by nimisha-yadav** [comment]
Hey, I've added the video in the readme, please check. Thanks

**Review by Nitesh-thapliyal — APPROVED** [review]
LGTM!

**Review by archithdwij — APPROVED** [review]
A very useful automation to make life easier 👏 Nice work @nimisha-yadav Congratulations on getting your PR merged!

**Comment by archithdwij** [comment]
@all-contributors Please add @nimisha-yadav for code, idea, infra, design

**Pull request merged**
